### ISSUE TITLE
Mac系统安装Java开发环境(JDK)

### ISSUE THREAD

**Issue by RainScorpio** [if-information/if_Java#2]
Mac 版本 10.13.3
 Java 开发平台: Java SE
 安装版本: jdk-8u152-macosx-x64.dmg
 安装时间: 2018.01.24

**Comment by RainScorpio** [comment]
# C01_安装之前
> 我是第一次安装Java环境, 在查找资料和安装的过程中, 我产生了一些疑问.

### 1. Mac系统是否自带Java环境?

> [如何确定 Mac 上是否安装了 Java?](https://java.com/zh_CN/download/faq/java_mac.xml#havejava)

> Mac OS X 10.6 和更低版本：
> &nbsp;&nbsp;&nbsp;&nbsp;	随 Mac OS 预安装了适用于 Apple 的 Java。 > <br>
> Mac OS X 10.7 (Lion) 和更高版本：
 &nbsp;&nbsp;&nbsp;&nbsp;	Mac OS X 版本 10.7 和更高版本中没有预安装 Java。要从 Oracle 获取最新的 Java，您需要 Mac OS X 10.7.3 和更高版本。 如果您已有 Java 7 或更高版本，则在系统首选项(系统偏好设置)下将看到 Java 图标。

> Java 版本 6 和更低版本将在 Java Preferences.app 中列出，位于 Mac 的“应用程序”>“实用工具”文件夹下。


虽然官方资料上说, Mac OS X 10.7以及更高版本已经不自带Java环境了, 需要自己安装. 但是在 `/System/Library/Frameworks/JavaVM.framework` 目录中依然有和Java相关的文件. **我不知道这个目录有什么作用?** 自己安装的Java环境也不在这个目录下. 网上很多资料都说这是Mac的默认的Java环境路径. 但Mac已经都不自带Java环境了啊!

还有`/System/Library/Java` 目录也不知道有什么作用

--

### 2. 没有自己安装Java环境, IntelliJ IDEA是否可以运行Java程序?

在我的Mac系统上是不可以的. 

在没有自己安装Java环境下, IntelliJ IDEA找不到JDK的安装路径.
当Java环境安装完成后, IntelliJ IDEA就自动匹配了JDK的安装路径.(此时我并没有设置任何环境变量, 就只是安装)

--

### 3. Java的开发平台有三个, 我应该安装哪一个?

Java的三个开发平台:

* Java SE : Java平台标准版,是另外两个平台的基础. Java SE 包含 Java 编程语言库的核心. 主要用于开发客户端（桌面应用软件)
* Java EE : Java平台企业版, Java EE包含Java SE中的类，还包含用于开发企业级应用的类, 主要用于Java Web 的开发.
* Java ME : Java平台微型版, 只包含Java SE中的一部分类，主要用于嵌入式系统和移动平台的开发.

**Java SE更适合刚学习Java的同学.**

--

### 4. 开发平台的JDK有很多个版本, 我应该安装哪一个?

Java SE 9是2017年7月发布, 对于目前来说版本太新, 而公司一般不会马上更新Java版本. 
Java SE 8是2014年3月发布, 2016年10月最后更新. 我个人认为安装Java SE 8 比较适合.

--
### 5. 在我当前的Mac系统上, 没有配置环境变量, 也能正常使用Java命令. 不知道为什么?

所有资料都说要设置环境变量(`JAVA_HOME`, `PATH`, `CLASSPATH`)才能使用Java命令. 但我在安装完成后, 没有配置环境变量, 也能正常使用Java命令. **不知道为什么?** 根据环境变量的作用, 推测在安装过程中自动的设置了环境变量. 但是目前还没有找到在哪个文件中设置了这些环境变量

**Comment by RainScorpio** [comment]
# C02_安装步骤

### 第一步: 从官网下载Java SE 8 的 JDK

> 由于Java SE 8 不是最新版本, 所以需要在历史版本中寻找.

> [Java SE 最新版本下载页面](http://www.oracle.com/technetwork/cn/java/javase/downloads/index.html)
		
		 

#### 查找JDK的历史版本

* 在 [Java SE 最新版本下载页面](http://www.oracle.com/technetwork/cn/java/javase/downloads/index.html) 的下面有一个 "Java 存档"的标题, 点击旁边的下载 

* 进入 Java 历史版本的页面, 选择Java SE 8版本, 进入[Java SE 8下载页面](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html?ssSourceSiteId=otncn)
* 选择要下载的版本即可.

#### JDK or JRE

在下载页面你会发现同一个版本(比如: 8u152)会有三个不同的下载:

* Java SE Development Kit 8u152
  Java SE 开发工具 8u152
	
* Java SE Runtime Environment 8u152
	Java SE 运行环境 8u152
	
* Server JRE (Java SE Runtime Environment) 8u152

	
不知道大家有没有从名字上推测出来需要下载哪一个呢🤔?

> Java SE 最新版本下载页面中有以下说明:
> 
> 我需要哪个 Java 软件包？
> 
>
>* 软件开发人员：JDK (Java SE Development Kit)。面向 Java 开发人员。包括一个完整的 JRE 以及用于开发、调试和监视 Java 应用的工具。
	
>* 在服务器上运行应用的管理员：Server JRE (Server Java Runtime Environment) 用于在服务器上部署 Java 应用。包括 JVM 监视工具以及服务器应用通常所需的工具，但不包括浏览器集成（Java 插件）、自动更新及安装程序。更多信息 ￼
		
>* 在桌面上运行 Java 的最终用户：JRE：(Java Runtime Environment)。可满足大多数最终用户需要。包含在系统上运行 Java 应用所需的一切内容。




	
```
8u152是什么意思呢?

	* 8 代表 Java SE的版本号
	* u 代表 update, 更新的意思,就是说这个JDK(或JRE)不是初始版本, 而是后期更新过的版本.
	* 152 代表 2015年第2次更新
	* 合起来的意思就是: Java SE 8的2015年第2次更新版本.

```


在 `Java SE Development Kit 8u152` 下选择对应系统版本的JDK进行下载. 
**注意**在下载之前必须点选 `Accept License Agreement`(接受许可协议).


--

### 第二步: 安装JDK

双击.dmg安装程序就行了. 一直点击下一步, 就OK了.

--

### 第三步: 验证安装完成

**方法1:**

打开系统偏好设置, 在最下面发现Java的图标, 说明安装完成.

**方法2:**
使用 `java` 命令

```c
Rain-Pro:~ rain$ java
用法: java [-options] class [args...]
           (执行类)
   或  java [-options] -jar jarfile [args...]
           (执行 jar 文件)
           
// 我省略了大部分输出.            
           
Rain-Pro:~ rain$
```


**方法3:**
使用 `java -version` 命令查看当前Java版本.

```c
Rain-Pro:~ rain$ java -version // version要写全, 不可省略.
java version "1.8.0_152" // 在终端输出的是开发者内部版本号, 而对外都是 Java 8.
Java(TM) SE Runtime Environment (build 1.8.0_152-b16) // TM 是注册商标 Trade Mark
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode) // HotSpot是Java虚拟机的名称, mixed mode代表解释与编译 混合的执行模式, 默认使用这种模式
Rain-Pro:~ rain$ 
```
> 参考资料:
>  [HotSpot是什么?](http://xiaomogui.iteye.com/blog/857821)

**Comment by RainScorpio** [comment]
# C03_设置环境变量

> 在我当前的Mac版本中, 只安装了一个JDK, 此时不需要设置环境变量也能开发和调试Java程序.

> 在此先记录下环境变量的设置.

在 ~ 目录(用户根目录)下创建.bash_profile文件.

```c
Rain-Pro:~ rain$ touch .bash_profile // 创建.bash_profile文件, touch命令创建一个空文件.
Rain-Pro:~ rain$ vim .bash_profile // 编辑.bash_profile文件
			
			// 以下是写入文件的内容(不包括注释)
			
			// JAVA_HOME变量用来配置JDK所在的安装目录
			JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
			
			
			// PATH变量用来指定可执行文件的完整路径 
			PATH=$JAVA_HOME/bin:$PATH:.  // $代表引用, $JAVA_HOME代表引用JAVA_HOME变量的值
			// : 用来分隔不同的环境变量. 有点拼接的意思
			// bin:$PATH 中的PATH代表的是系统的环境变量.
			// $PATH:. 中的 . 代表当前目录, 也添加到当前的PATH环境变量中
			
			
			// CLASSPATH用来指定java程序中所使用的类库
			CLASSPATH=$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:.
			// tools.jar  工具类库, 使用javac命令的时候会使用到tools.jar类库
			// dt.jar	运行环境的类库, swing会用到.
			
			// 声明环境变量
			export JAVA_HOME
			export PATH
			export CLASSPATH
		
Rain-Pro:~ rain$ source .bash_profile // 使环境变量生效		
		
``` 	

#### 为什么要在.bash_profile文件中设置Java环境变量?

> 参考资料: [/etc/profile、~/.bash_profile等几个文件的执行过程](http://blog.chinaunix.net/uid-14735472-id-3190130.html)

> ~/.bash_profile: 每个用户都可使用该文件输入专用于自己使用的shell信息,当用户登录时,该文件仅仅执行一次!默认情况下,他设置一些环境变量,执行用户的.bashrc文件。
 
> /etc/profile： 此文件为系统的每个用户设置环境信息,当用户第一次登录时,该文件被执行. 并从/etc/profile.d目录的配置文件中搜集shell的设置。

**Comment by yuancaoscott** [comment]
# C04_是不是注明一下安装JDK还是JRE

**Comment by RainScorpio** [comment]
# C05_在什么地方注明安装JDK还是JRE?
