### ISSUE TITLE
JAVA_HOME, PATH, CLASSPATH 环境变量的设置

### ISSUE THREAD

**Issue by RainScorpio** [if-information/if_Java#4]
* 所有资料都说要设置环境变量(JAVA_HOME, PATH, CLASSPATH)才能使用Java命令. 但我在安装完成后, 没有配置环境变量, 也能正常使用Java命令. **不知道为什么?**  
    
    ```
     Rain-Pro:~ rain$ echo $JAVA_HOME
                                           // 没有任何输出
     Rain-Pro:~ rain$ 
    ```

* 根据环境变量的作用, 推测在安装过程中自动的设置了环境变量. **但是目前还没有找到在哪个文件中设置了这些环境变量**

**Comment by yuancaoscott** [comment]
# C01_安装了哪个Java软件
@RainScorpio 
> 根据环境变量的作用, 推测在安装过程中自动的设置了环境变量

能说明是具体安装了哪个软件吗?

**Comment by RainScorpio** [comment]
# C02_安装的Java SE 8 的 JDK

详情如下: 
* Mac 版本 10.13.3
* Java 开发平台: Java SE
* 安装版本: jdk-8u152-macosx-x64.dmg
* 安装时间: 2018.01.24
